package entity;
// Generated Jul 5, 2017 8:21:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sorteo generated by hbm2java
 */
public class Sorteo  implements java.io.Serializable {


     private int idSorteo;
     private Pozo pozo;
     private String combinacion;
     private Date fechaSorteo;
     private Set juegos = new HashSet(0);

    public Sorteo() {
    }

	
    public Sorteo(int idSorteo, Pozo pozo, String combinacion, Date fechaSorteo) {
        this.idSorteo = idSorteo;
        this.pozo = pozo;
        this.combinacion = combinacion;
        this.fechaSorteo = fechaSorteo;
    }
    public Sorteo(int idSorteo, Pozo pozo, String combinacion, Date fechaSorteo, Set juegos) {
       this.idSorteo = idSorteo;
       this.pozo = pozo;
       this.combinacion = combinacion;
       this.fechaSorteo = fechaSorteo;
       this.juegos = juegos;
    }
   
    public int getIdSorteo() {
        return this.idSorteo;
    }
    
    public void setIdSorteo(int idSorteo) {
        this.idSorteo = idSorteo;
    }
    public Pozo getPozo() {
        return this.pozo;
    }
    
    public void setPozo(Pozo pozo) {
        this.pozo = pozo;
    }
    public String getCombinacion() {
        return this.combinacion;
    }
    
    public void setCombinacion(String combinacion) {
        this.combinacion = combinacion;
    }
    public Date getFechaSorteo() {
        return this.fechaSorteo;
    }
    
    public void setFechaSorteo(Date fechaSorteo) {
        this.fechaSorteo = fechaSorteo;
    }
    public Set getJuegos() {
        return this.juegos;
    }
    
    public void setJuegos(Set juegos) {
        this.juegos = juegos;
    }




}


